#!/bin/sh

set -e

EULA_URL="https://raw.githubusercontent.com/MLSTidbits/reel/refs/heads/main/src/makemkv/eula.license"
TMP_EULA="/tmp/makemkv_eula.license"

ROWS=$(tput lines)
COLS=$(tput cols)

curl -sSL "$EULA_URL" -o "$TMP_EULA"

case "$1" in
    configure|upgrade                            )
        if [ "$1" = "configure" ]; then
            if [ -f /usr/share/doc/makemkv-bin/eula.license.gz ] ; then
                echo "EULA already accepted, skipping"
            else
                if command -v curl >/dev/null 2>&1 ; then
                    curl -sSL "$EULA_URL" -o "$TMP_EULA"
                elif command -v wget >/dev/null 2>&1 ; then
                    wget -qO "$TMP_EULA" "$EULA_URL"
                else
                    echo "ERROR: neither curl nor wget is available." >&2
                    rm -f "$TMP_EULA"
                    exit 1
                fi
                whiptail --title "MakeMKV EULA" --textbox --scrolltext "$TMP_EULA" "$ROWS" "$COLS"
                rm -f "$TMP_EULA"

                if ! whiptail --title "MakeMKV EULA" --yesno "Do you accept the MakeMKV EULA?" 10 60 ; then
                    echo "EULA not accepted, aborting installation"
                fi

            fi
        fi

    ;;
    failed-upgrade                               ) ;;
    abort-upgrade|abort-deconfigure|abort-remove ) ;;
    *                                            )
        echo "Unsupported option $1" ; exit 1
    ;;
esac

exit 0
