#!/usr/bin/env bash

# Start the MakeMKV GUI from the /usr/lib/makemkv-gtk

# Uncomment the following line to enable debugging output
# set -xo pipefail

APP_DIR="/usr/lib/reel"
PYTHONPATH="${APP_DIR}${PYTHONPATH:+:$PYTHONPATH}"

export PYTHONPATH

exec python3 "${APP_DIR}/main.py" "$@"
